### ISSUE TITLE
Make a sample of a working app

### ISSUE THREAD

**Issue by Deilan** [kimamula/ts-transformer-keys#7]
Please make a sample of a working app. Right now any usage results in the following error occur ([Repo with a demo](https://github.com/deilan-issues-samples/ts-transformer-keys-issue-7)):

```
TypeError: ts_transformer_keys_1.keys is not a function
    at Object.<anonymous> (c:\Dev\ts-transformer-keys-issue-7\src\index.ts:26:21)
    at Module._compile (module.js:571:32)
    at Module.m._compile (c:\Dev\ts-transformer-keys-issue-7\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (c:\Dev\ts-transformer-keys-issue-7\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (c:\Dev\ts-transformer-keys-issue-7\node_modules\ts-node\src\_bin.ts:182:12)
```

or

```
TSError: ⨯ Unable to compile TypeScript
File 'c:/Dev/ts-transformer-keys-issue-7/node_modules/ts-transformer-keys/index.ts' is not under 'rootDir' 'C:/Dev/ts-transformer-keys-issue-7/src'. 'rootDir' is expected to contain all source files. (6059)
    at getOutput (c:\Dev\ts-transformer-keys-issue-7\node_modules\ts-node\src\index.ts:307:15)
    at c:\Dev\ts-transformer-keys-issue-7\node_modules\ts-node\src\index.ts:336:16
    at Object.compile (c:\Dev\ts-transformer-keys-issue-7\node_modules\ts-node\src\index.ts:498:11)
    at Module.m._compile (c:\Dev\ts-transformer-keys-issue-7\node_modules\ts-node\src\index.ts:392:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (c:\Dev\ts-transformer-keys-issue-7\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
```

**Comment by kimamula** [comment]
Please read https://github.com/kimamula/ts-transformer-keys#how-to-use-the-custom-transformer thoroughly.
Working example is https://github.com/kimamula/ts-transformer-keys/blob/master/test/compile.ts, whose compilation result is examined with `npm test`.

**Comment by kimamula** [comment]
If you are using Windows, the issue is probably fixed by [this commit](https://github.com/kimamula/ts-transformer-keys/pull/10/commits/8c6145e1735278280ed5c3a2d56e0c27a31caf91).
Please try v0.3.1.

**Comment by trombitas** [comment]
Any updates on this issue? 

I am using Angular 5 with Typescript 2.8.3 and ts_transformer_keys v0.3.3 and I am still getting this error on Windows: "TypeError: ts_transformer_keys_1.keys is not a function". 

Thank you!

**Comment by kimamula** [comment]
I have updated ["How to use the custom transformer" part of README](https://github.com/kimamula/ts-transformer-keys#how-to-use-the-custom-transformer) and included example usages with [webpack](https://github.com/kimamula/ts-transformer-keys/tree/master/examples/webpack), [Rollup](https://github.com/kimamula/ts-transformer-keys/tree/master/examples/rollup), and [ttypescript](https://github.com/kimamula/ts-transformer-keys/tree/master/examples/ttypescript) in this repo.

To use with Angular, I think you have to customize webpack configuration somehow.
